apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: local-quay
  namespace: local-quay
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
    - local-quay
