apiVersion: v1
kind: Secret
metadata:
  name: init-config-bundle-secret
  namespace: local-quay
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  config.yaml: |
    FEATURE_USER_INITIALIZE: true
    BROWSER_API_CALLS_XHR_ONLY: false
    SUPER_USERS:
    - quayadmin
    FEATURE_USER_CREATION: true
    FEATURE_SUPERUSERS_FULL_ACCESS: true
